app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('choose_mode/', choose_mode, name='choose_mode'),
    path('absensi/', absence, name='absence'),
    path('absensi/konfirmasi/', confirm_absence, name='confirm_absence'),
    path('absensi/konfirmasi_lembur/', confirm_overtime, name='confirm_overtime'),

    path('pengajuan_cuti/', pengajuan_cuti, name='pengajuan_cuti'),
    path('pengajuan_cuti/edit/<int:id>', edit_pengajuan_cuti, name='edit_pengajuan_cuti'),
    path('pengajuan_cuti/delete/<int:id>', delete_pengajuan_cuti, name='delete_pengajuan_cuti'),

    path('jadwal/', jadwal, name='jadwal'),
    path('presensi/', presensi, name='presensi'),

    path('pengajuan_izin/', pengajuan_izin, name='pengajuan_izin'),
    path('pengajuan_izin/edit/<int:id>', edit_pengajuan_izin, name='edit_pengajuan_izin'),
    path('pengajuan_izin/delete/<int:id>', delete_pengajuan_izin, name='delete_pengajuan_izin'),

    path('keluar_bentar/', keluar_bentar, name='keluar_bentar'),
    path('keluar_bentar/balik', balik_keluar_bentar, name='balik_keluar_bentar'),

    path('profil/<str:nik>', profile, name='profile'),

    path('pengajuan_lembur/', pengajuan_lembur, name='pengajuan_lembur'),
    path('pengajuan_lembur/<int:id>', detail_pengajuan_lembur, name='detail_pengajuan_lembur'),

    path('save_fcm_token/', save_fcm_token, name='save_fcm_token')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from cms.views import err404 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include('app.urls')),

    path('admins/', include('cms.urls')),

    path('payroll/', include('payroll.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = err404

app/models.py
from django.db import models
from utils.image import compress_image

# Create your models here.
class Users(models.Model):
    nik = models.CharField(max_length=20, unique=True, primary_key=True)
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='img/')
    divisi = models.CharField(max_length=100,null=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    password = models.CharField(max_length=100)
    face_encoding = models.BinaryField(null=True, blank=True)
    is_admin = models.IntegerField(choices=[
            (0, 'User'),
            (1, 'Admin'),
            (2, 'Super User')
        ],
        default=0
    )
    is_accountant = models.BooleanField(default=False)
    telegram_chat_id = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Admins(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    is_superadmin = models.BooleanField(default=False)
    nik = models.ForeignKey(Users, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class InAbsences(models.Model):
    id = models.AutoField(primary_key=True)
    nik = models.ForeignKey(Users, on_delete=models.CASCADE)
    date_in = models.DateTimeField()
    status_in = models.CharField(max_length=20)
    date_out = models.DateTimeField(null=True, blank=True)
    status_out = models.CharField(max_length=20, null=True, blank=True)
    schedule = models.ForeignKey('cms.MasterSchedules', null=True, on_delete=models.SET_NULL)
    shift_order = models.PositiveSmallIntegerField(null=True, blank=True)
    is_from_leave = models.BooleanField(default=False)
    leave_request = models.ForeignKey(
        'cms.LeaveRequests',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    is_from_permission = models.BooleanField(default=False)
    permission_request = models.ForeignKey(
        'app.PermissionRequests',
        null=True, blank=True,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class OutAbsences(models.Model):
    id = models.AutoField(primary_key=True)
    nik = models.ForeignKey(Users, on_delete=models.CASCADE)
    date = models.DateTimeField()
    status = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PermissionRequests(models.Model):
    id = models.AutoField(primary_key=True)
    nik = models.ForeignKey('app.Users', on_delete=models.CASCADE)
    permission_type = models.ForeignKey('cms.MasterPermission', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='bukti_izin/', null=True, blank=True)
    note = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    reason = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=20, default='Pending')
    user_target = models.ForeignKey('app.Users', related_name='permission_approver', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.photo:
            self.photo = compress_image(self.photo)
        super().save(*args, **kwargs)

class OutPermission(models.Model):
    nik = models.ForeignKey('app.Users', on_delete=models.CASCADE)

    date = models.DateField()
    time_out = models.DateTimeField()
    time_in = models.DateTimeField(null=True, blank=True)

    duration_minutes = models.IntegerField(null=True, blank=True)

    reason = models.TextField()

    status = models.CharField(
        max_length=20,
        choices=[
            ('OUT', 'Sedang Keluar'),
            ('RETURN', 'Sudah Kembali'),
            ('CANCEL', 'Dibatalkan'),
        ],
        default='OUT'
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Overtimes(models.Model):
    id = models.AutoField(primary_key=True)
    nik = models.ForeignKey(Users,on_delete=models.CASCADE,related_name="overtimes")
    overtime_date = models.DateField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True, blank=True)
    duration_minutes = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=[
            ("DRAFT", "Draft"),
            ("SUBMITTED", "Submitted"),
            ("DIVISI APPROVED", "Divisi Approved"),
            ("APPROVED", "Approved"),
            ("REJECTED", "Rejected"),
        ],
        default="DRAFT"
    )
    approved_by = models.ForeignKey(Users,null=True,blank=True,on_delete=models.SET_NULL, related_name="approved_overtimes")
    approved_at = models.DateTimeField(null=True, blank=True)
    reason = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

templates/user/profile/index.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            
            <div class="card shadow-lg border-0">
                <div class="card-header bg-warning text-dark py-3">
                    <h4 class="mb-0"><i class="fas fa-pencil-alt me-2"></i> {{ detail_user.name }}</h4>
                </div>
                
                <div class="card-body p-4">
                    
                    <form method="POST" enctype="multipart/form-data" action="{% url 'profile' detail_user.nik %}">
                        {% csrf_token %}
                        
                        <div class="row">
                            <div class="col-md-5 text-center border-end">
                                
                                <h5 class="text-primary mb-3">Foto Profil</h5>
                                <img src="{{ detail_user.photo.url }}" alt="Foto Profil Saat Ini" 
                                     class="profile-photo mb-3" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%; border: 3px solid #ccc;">

                                <div class="mb-3">
                                    <small class="form-text text-muted">Foto tidak bisa diubah kecuali terdapat ketidakcocokan data saat melakukan presensi.</small>
                                    <small class="form-text text-danger">Minta tolong Mas Lexca untuk penyesuaian foto.</small>
                                    
                                </div>
                                
                                <hr class="my-4 d-md-none">
                            </div>

                            <div class="col-md-7">
                                
                                <h5 class="text-primary mb-3">Data Pribadi</h5>

                                <div class="mb-3">
                                    <label for="id_nik" class="form-label">NIK</label>
                                    <input type="text" class="form-control" id="id_nik" name="nik" 
                                           value="{{ detail_user.nik }}" readonly>
                                </div>

                                <div class="mb-3">
                                    <label for="id_name" class="form-label">Nama Lengkap</label>
                                    <input type="text" class="form-control" id="id_name" name="name" 
                                           value="{{ detail_user.name }}" required readonly>
                                </div>

                                <div class="mb-3">
                                    <label for="id_divisi" class="form-label">Divisi</label>
                                    <select class="form-control" id="id_divisi" name="divisi" required readonly>
                                        <option value="{{ division_detail.id }}" selected>{{ division_detail.name }}</option>
                                    </select>
                                </div>

                                <hr class="my-4">

                                <h5 class="text-primary mb-3">Data Kontak</h5>

                                <div class="mb-3">
                                    <label for="id_email" class="form-label">Email</label>
                                    <input type="email" class="form-control" id="id_email" name="email" 
                                           value="{{ detail_user.email }}" required>
                                </div>

                                <div class="mb-3">
                                    <label for="telegram_chat_id" class="form-label">Telegram Chat ID</label>
                                    <input type="text" class="form-control" id="telegram_chat_id" name="telegram_chat_id" 
                                           value="{{ detail_user.telegram_chat_id }}">
                                </div>

                                <hr class="my-4">

                                <h5 class="text-primary mb-3">Pengaturan Akun</h5>
                                <div class="mb-3">
                                    <label for="id_password" class="form-label">Password Baru</label>
                                    <input type="password" class="form-control" id="id_password" name="password" 
                                           placeholder="Kosongkan jika tidak ingin mengganti password">
                                    <small class="form-text text-danger">Isi hanya jika Anda ingin mengubah password.</small>
                                </div>
                            </div>
                        </div>

                        <hr class="mt-4 mb-4">
                        
                        <div class="text-center">
                            <button type="submit" class="btn btn-success me-3">
                                <i class="fas fa-save me-1"></i> Simpan 
                            </button>
                            <a href="{% url 'jadwal' %}" class="btn btn-danger">
                                <i class="fas fa-times me-1"></i> Batal
                            </a>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
<script>
    {% for message in messages %}
    Swal.fire({
        icon: "{{ message.tags }}",  
        title: "{{ message.tags|capfirst }}",
        text: "{{ message }}",
        showConfirmButton: false,
        timer: 3000
    });
    {% endfor %}
</script>
{% endif %}
{% endblock %}